version: '3'

services:
  nats-alpine:  # Define a new service for NATS Alpine
    image: nats:alpine
    ports:
      - "4222:4222"  # Expose port 4222 for NATS
    restart: always
    networks:
      - xxx
  redis-alpine:
    image: redis:alpine
    ports:
      - "6379:6379"  # Expose port 6379 for Redis
    restart: always
    volumes:
      - redis_data:/data
    networks:
      - xxx  # Assign the Redis service to the redis-network

  backend_fiber:
    image: golang:1.21.0-alpine
    build: .
    restart: always
    env_file:
      - .env.dev
   
    expose:
      - "3000"
    depends_on:
      - redis-alpine  # Specify Redis Alpine as a dependency
      - nats-alpine
    networks:
      - xxx  # Connect the backend_fiber service to the redis-network

volumes:
  redis_data:

networks:
  xxx:
    driver: bridge
