version: '3'

services:
  redis-alpine:
    image: redis:alpine
    ports:
      - "6379:6379"  # Expose port 6379 for Redis
    restart: always
    volumes:
      - redis_data:/data
    networks:
      - redis-network  # Assign the Redis service to the redis-network

  backend_fiber:
    image: golang:1.21.0-alpine
    build: .
    restart: always
    env_file:
      - .env
    environment:
      - VIRTUAL_HOST=localhost
      - VIRTUAL_PORT=3000
    expose:
      - "3000"
    depends_on:
      - redis-alpine  # Specify Redis Alpine as a dependency
    networks:
      - redis-network  # Connect the backend_fiber service to the redis-network

volumes:
  redis_data:

networks:
  redis-network:
    driver: bridge
